In [1]:
import pandas as pd
import numpy as np
import scipy.stats as sps 
import matplotlib.pyplot as plt 
import seaborn as sns
import sklearn as skl
from sklearn import preprocessing 
%matplotlib inline

In [2]:
%%time
data = pd.read_csv('NYP_45_var_revised.csv')

Wall time: 21.1 s

In [3]:
normalized_data = (data - data.mean()) / data.std()

In [4]:
normalized_data.head()

,Unnamed: 0,new,area_level,meanvalue,meanvalvalue,val_level,meanLTFRONT,meanLTDEPTH,meanBLDFRONT,meanBLDDEPTH,...,r7_bytaxclass,r7_b,r8_byzip5,r8_byzip3,r8_bytaxclass,r8_b,r9_byzip5,r9_byzip3,r9_bytaxclass,r9_b
0,-1.732048,9.689232,9.803657,1.614149,1.614149,3.176935,0.85454,7.736625,0.747486,0.828002,...,-0.112658,-0.065758,0.055029,0.047294,0.012761,0.034259,-0.047669,-0.016185,-0.011280,-0.014436
1,-1.732045,-0.694641,-0.642834,13.955435,13.955435,4.464087,0.85454,1.418657,0.747486,0.828002,...,22.146310,12.782065,0.592842,0.395861,0.251608,0.281342,-0.004117,0.011990,-0.006674,0.012419
2,-1.732042,6.255115,6.669710,8.995630,8.995630,3.946267,0.85454,5.890635,0.747486,0.828002,...,0.038223,0.021331,-0.025740,-0.005054,-0.023109,-0.002848,-0.018801,0.002491,-0.008227,0.003365
3,-1.732039,7.111097,7.192034,3.362357,3.362357,3.369268,0.85454,5.721635,0.747486,0.828002,...,-0.079325,-0.046518,0.064324,0.053319,0.016889,0.038530,0.128194,0.097587,0.007317,0.094003
4,-1.732035,11.869947,12.415280,24.422283,24.422283,5.544111,0.85454,14.938589,0.747486,0.828002,...,0.316434,0.181913,8.338051,5.415676,3.691309,3.839657,23.763619,15.388211,2.506689,14.667834

In [5]:
normalized_data.drop('Unnamed: 0',axis=1, inplace=True)
normalized_data.head()

,new,area_level,meanvalue,meanvalvalue,val_level,meanLTFRONT,meanLTDEPTH,meanBLDFRONT,meanBLDDEPTH,r1_all,...,r7_bytaxclass,r7_b,r8_byzip5,r8_byzip3,r8_bytaxclass,r8_b,r9_byzip5,r9_byzip3,r9_bytaxclass,r9_b
0,9.689232,9.803657,1.614149,1.614149,3.176935,0.85454,7.736625,0.747486,0.828002,-0.071548,...,-0.112658,-0.065758,0.055029,0.047294,0.012761,0.034259,-0.047669,-0.016185,-0.011280,-0.014436
1,-0.694641,-0.642834,13.955435,13.955435,4.464087,0.85454,1.418657,0.747486,0.828002,11.868695,...,22.146310,12.782065,0.592842,0.395861,0.251608,0.281342,-0.004117,0.011990,-0.006674,0.012419
2,6.255115,6.669710,8.995630,8.995630,3.946267,0.85454,5.890635,0.747486,0.828002,0.009389,...,0.038223,0.021331,-0.025740,-0.005054,-0.023109,-0.002848,-0.018801,0.002491,-0.008227,0.003365
3,7.111097,7.192034,3.362357,3.362357,3.369268,0.85454,5.721635,0.747486,0.828002,-0.053667,...,-0.079325,-0.046518,0.064324,0.053319,0.016889,0.038530,0.128194,0.097587,0.007317,0.094003
4,11.869947,12.415280,24.422283,24.422283,5.544111,0.85454,14.938589,0.747486,0.828002,0.158628,...,0.316434,0.181913,8.338051,5.415676,3.691309,3.839657,23.763619,15.388211,2.506689,14.667834

In [6]:
normalized_data.describe()

,new,area_level,meanvalue,meanvalvalue,val_level,meanLTFRONT,meanLTDEPTH,meanBLDFRONT,meanBLDDEPTH,r1_all,...,r7_bytaxclass,r7_b,r8_byzip5,r8_byzip3,r8_bytaxclass,r8_b,r9_byzip5,r9_byzip3,r9_bytaxclass,r9_b
count,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,...,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06,1.070994e+06
mean,-9.098309e-13,3.586212e-13,-5.012489e-15,-5.012489e-15,4.192578e-15,-1.912676e-13,-1.048997e-13,-3.356755e-12,-1.680529e-12,7.177336e-15,...,8.844549e-15,8.879619e-15,-7.649944e-15,4.297462e-15,-4.016571e-16,-1.568602e-16,9.847975e-16,6.281965e-16,9.391656e-16,3.996953e-17
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,...,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
min,-9.697779e-01,-6.428339e-01,-5.888915e-02,-5.888915e-02,-2.311954e+00,-7.384579e-01,-1.428329e+00,-6.581570e-01,-8.720542e-01,-8.654102e-02,...,-1.406087e-01,-8.189083e-02,-6.673232e-02,-3.162137e-02,-4.131318e-02,-2.168026e-02,-5.752847e-02,-2.256375e-02,-1.232248e-02,-2.051526e-02
25%,-9.341573e-02,-1.205094e-01,-4.194112e-02,-4.194112e-02,-5.513666e-01,-6.195774e-01,-1.803350e-01,-6.221149e-01,-6.788661e-01,-5.915048e-02,...,-9.101221e-02,-5.751823e-02,-4.385631e-02,-2.098265e-02,-2.548484e-02,-1.463812e-02,-4.025851e-02,-1.566439e-02,-7.866358e-03,-1.421896e-02
50%,4.924788e-02,-1.205094e-01,-3.519309e-02,-3.519309e-02,1.439913e-01,-6.195774e-01,-1.413352e-01,-6.221149e-01,-6.788661e-01,-3.087301e-02,...,-4.053087e-02,-3.917345e-02,-2.408328e-02,-1.341812e-02,-8.785615e-03,-1.034735e-02,-2.389982e-02,-1.048633e-02,-2.737368e-03,-9.805678e-03
75%,4.924788e-02,-1.205094e-01,-2.589955e-02,-2.589955e-02,6.914007e-01,8.545405e-01,-7.633549e-02,7.474864e-01,8.280015e-01,2.134833e-03,...,1.345067e-02,-1.611243e-02,-6.742373e-03,-7.402934e-03,2.456167e-03,-5.702499e-03,-8.969363e-03,-5.627796e-03,9.393796e-04,-5.186594e-03
max,1.009226e+02,1.032998e+02,5.497514e+02,5.497514e+02,7.141955e+00,6.679684e+00,1.285450e+02,1.972919e+00,1.909855e+00,3.062488e+02,...,7.242346e+02,6.758868e+02,5.045268e+02,7.371808e+02,8.299417e+02,5.680460e+02,5.010726e+02,8.705702e+02,1.027956e+03,8.952233e+02

In [7]:
from sklearn.decomposition import PCA

In [8]:
features = ['FULLVAL_r1', 'FULLVAL_r2', 'FULLVAL_r3', 'AVLAND_r4', 'AVLAND_r5',
       'AVLAND_r6', 'AVTOT_r7', 'AVTOT_r8', 'AVTOT_r9', 'r1_byzip5',
       'r1_byzip3', 'r1_bytaxclass', 'r1_b', 'r2_byzip5', 'r2_byzip3',
       'r2_bytaxclass', 'r2_b', 'r3_byzip5', 'r3_byzip3', 'r3_bytaxclass',
       'r3_b', 'r4_byzip5', 'r4_byzip3', 'r4_bytaxclass', 'r4_b', 'r5_byzip5',
       'r5_byzip3', 'r5_bytaxclass', 'r5_b', 'r6_byzip5', 'r6_byzip3',
       'r6_bytaxclass', 'r6_b', 'r7_byzip5', 'r7_byzip3', 'r7_bytaxclass',
       'r7_b', 'r8_byzip5', 'r8_byzip3', 'r8_bytaxclass', 'r8_b', 'r9_byzip5',
       'r9_byzip3', 'r9_bytaxclass', 'r9_b']
x = data.loc[:,features].values

D:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1472: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)

In [9]:
pca = PCA(n_components = 7)
principalComponents = pca.fit_transform(normalized_data)
DF = pd.DataFrame(data = principalComponents)

In [10]:
DF.shape

(1070994, 7)

In [11]:
DF.head()

           0          1          2          3          4          5          6
0   0.564646   0.326122   4.176639  -5.824908  -5.496519 -10.747845  -7.110954
1   5.054186  64.146938  -1.145145   0.930923   4.487133  -9.043992  -1.739356
2   0.801472   2.664531   5.647312  -7.334524  -6.872048  -7.886802  -5.519797
3   0.960841   0.842309   3.954544  -5.244671  -4.987466  -8.194002  -5.222719
4  68.701486   4.293685  14.018286 -19.038046 -25.279901 -26.126968  25.460930

In [12]:
pca.explained_variance_ratio_

array([0.41342977, 0.20092429, 0.06067362, 0.05888254, 0.05479944,
       0.04718128, 0.03500744])

In [13]:
sum(pca.explained_variance_ratio_)

0.8708983820718132

In [14]:
finalDF = (DF-DF.mean())/DF.std()
finalDF.head()

           0          1         2          3          4          5          6
0   0.119503   0.099007  2.307439  -3.266622  -3.195235  -6.733481  -5.171908
1   1.069679  19.474344 -0.632650   0.522064   2.608459  -5.666024  -1.265061
2   0.169625   0.808924  3.119931  -4.113218  -3.994857  -4.941049  -4.014635
3   0.203354   0.255716  2.184739  -2.941224  -2.899312  -5.133509  -3.798566
4  14.540133   1.303518  7.744584 -10.676582 -14.695704 -16.368438  18.518134

In [15]:
newDF = abs(finalDF)
newDF.head()

           0          1         2          3          4          5          6
0   0.119503   0.099007  2.307439   3.266622   3.195235   6.733481   5.171908
1   1.069679  19.474344  0.632650   0.522064   2.608459   5.666024   1.265061
2   0.169625   0.808924  3.119931   4.113218   3.994857   4.941049   4.014635
3   0.203354   0.255716  2.184739   2.941224   2.899312   5.133509   3.798566
4  14.540133   1.303518  7.744584  10.676582  14.695704  16.368438  18.518134

In [16]:
newDF['Score1'] = newDF.transpose().sum()
newDF.head()

,0,1,2,3,4,5,6,Score1
0,0.119503,0.099007,2.307439,3.266622,3.195235,6.733481,5.171908,20.893195
1,1.069679,19.474344,0.632650,0.522064,2.608459,5.666024,1.265061,31.238281
2,0.169625,0.808924,3.119931,4.113218,3.994857,4.941049,4.014635,21.162240
3,0.203354,0.255716,2.184739,2.941224,2.899312,5.133509,3.798566,17.416420
4,14.540133,1.303518,7.744584,10.676582,14.695704,16.368438,18.518134,83.847093

In [17]:
newDF['Score2'] = pow(finalDF,2).transpose().sum()

In [18]:
newDF['Score2'] = pow(newDF['Score2'],0.5)
newDF.head()

,0,1,2,3,4,5,6,Score1,Score2
0,0.119503,0.099007,2.307439,3.266622,3.195235,6.733481,5.171908,20.893195,9.915498
1,1.069679,19.474344,0.632650,0.522064,2.608459,5.666024,1.265061,31.238281,20.532300
2,0.169625,0.808924,3.119931,4.113218,3.994857,4.941049,4.014635,21.162240,9.155644
3,0.203354,0.255716,2.184739,2.941224,2.899312,5.133509,3.798566,17.416420,7.919511
4,14.540133,1.303518,7.744584,10.676582,14.695704,16.368438,18.518134,83.847093,34.840973

In [19]:
newDF['RECORD'] = newDF.index + 1

In [20]:
newDF.sort_values('Score2',ascending = False).head()

,0,1,2,3,4,5,6,Score1,Score2,RECORD
632815,809.974726,80.565997,19.180533,473.638498,162.980559,105.299716,333.187423,1984.827452,1017.799493,632816
565391,68.076286,702.230760,234.550456,171.101004,258.840767,418.669265,20.758297,1874.226835,908.165895,565392
585117,217.946753,16.012009,45.145521,368.208686,399.048489,109.836933,254.193226,1410.391617,649.069311,585118
1067359,17.448271,491.429071,187.079541,184.220152,210.878004,241.550296,3.354619,1335.959954,643.094180,1067360
85885,275.588756,19.891594,11.403108,25.246142,98.791884,127.803612,442.767981,1001.493077,547.036855,85886

In [21]:
newDF.reset_index()

,index,0,1,2,3,4,5,6,Score1,Score2,RECORD
0,0,0.119503,0.099007,2.307439,3.266622,3.195235,6.733481,5.171908,20.893195,9.915498,1
1,1,1.069679,19.474344,0.632650,0.522064,2.608459,5.666024,1.265061,31.238281,20.532300,2
2,2,0.169625,0.808924,3.119931,4.113218,3.994857,4.941049,4.014635,21.162240,9.155644,3
3,3,0.203354,0.255716,2.184739,2.941224,2.899312,5.133509,3.798566,17.416420,7.919511,4
4,4,14.540133,1.303518,7.744584,10.676582,14.695704,16.368438,18.518134,83.847093,34.840973,5
5,5,0.060350,0.265155,0.863885,1.234706,1.157430,2.163547,1.800895,7.545967,3.407131,6
6,6,7.379761,0.450533,1.465088,1.540632,3.823265,5.730002,12.114912,32.504193,15.918707,7
7,7,0.472339,0.472037,1.135673,1.684090,1.193999,1.982002,1.110724,8.050863,3.340585,8
8,8,0.023671,0.011300,0.614190,0.044328,0.218349,0.065942,0.073381,1.051161,0.661281,9
9,9,0.020565,0.018899,0.625406,0.003542,0.180121,0.083427,0.092461,1.024421,0.663233,10
10,10,0.005481,0.056459,0.752541,0.175376,0.055388,0.318220,0.265698,1.629163,0.880466,11
11,11,0.043696,0.067676,0.540839,0.247032,0.370289,0.197565,0.144897,1.611994,0.746433,12
12,12,0.033345,0.026956,0.540593,0.131807,0.273340,0.054245,0.020146,1.080432,0.624112,13
13,13,0.033978,0.033280,0.540812,0.134937,0.275458,0.055942,0.021889,1.096296,0.626445,14
14,14,0.019447,0.026949,0.701705,0.075947,0.100244,0.202752,0.187415,1.314459,0.765209,15
15,15,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,16
16,16,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,17
17,17,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,18
18,18,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,19
19,19,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,20
20,20,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,21
21,21,0.009399,0.047091,0.671356,0.074890,0.136433,0.160597,0.155204,1.254969,0.726035,22
22,22,0.009415,0.047031,0.671323,0.074819,0.136453,0.160591,0.155195,1.254827,0.725994,23
23,23,0.008731,0.061717,0.636055,0.053131,0.157727,0.105049,0.113922,1.136332,0.678355,24
24,24,0.008731,0.061717,0.636055,0.053131,0.157727,0.105049,0.113922,1.136332,0.678355,25
25,25,0.019710,0.025831,0.700934,0.074548,0.100872,0.202609,0.187214,1.311716,0.764327,26
26,26,0.019710,0.025831,0.700934,0.074548,0.100872,0.202609,0.187214,1.311716,0.764327,27
27,27,0.019710,0.025831,0.700934,0.074548,0.100872,0.202609,0.187214,1.311716,0.764327,28
28,28,0.019710,0.025831,0.700934,0.074548,0.100872,0.202609,0.187214,1.311716,0.764327,29
29,29,0.019781,0.025526,0.700723,0.074167,0.101043,0.202569,0.187159,1.310968,0.764087,30
...,...,...,...,...,...,...,...,...,...,...,...
1070964,1070964,0.016422,0.077886,0.511067,0.257311,0.405797,0.104125,0.255874,1.628482,0.758102,1070965
1070965,1070965,0.059325,0.088611,0.551776,0.331948,0.326481,0.076425,0.139485,1.574051,0.746930,1070966
1070966,1070966,0.006785,0.093687,0.274411,0.574907,0.719360,0.820885,0.814617,3.304651,1.506510,1070967
1070967,1070967,0.052208,0.104610,0.431991,0.551050,0.581946,0.576351,0.524676,2.822831,1.204187,1070968
1070968,1070968,0.000742,0.092835,0.450627,0.505687,0.669867,0.580138,0.620062,2.919958,1.279516,1070969
1070969,1070969,0.008393,0.091051,0.393308,0.473477,0.649101,0.584224,0.625581,2.825134,1.241464,1070970
1070970,1070970,0.001173,0.100107,0.418915,0.394327,0.533984,0.383086,0.456442,2.288034,0.990576,1070971
1070971,1070971,0.028747,0.061866,0.505087,0.446469,0.535049,0.410146,0.444140,2.431504,1.053973,1070972
1070972,1070972,0.013009,0.099970,0.439256,0.254856,0.395966,0.123155,0.263023,1.589235,0.713581,1070973
1070973,1070973,0.001736,0.104056,0.432408,0.205737,0.322467,0.019726,0.166181,1.252311,0.610021,1070974
1070974,1070974,0.012653,0.089038,0.431490,0.201970,0.336706,0.039637,0.195972,1.307465,0.623226,1070975
1070975,1070975,0.002980,0.100989,0.392634,0.351991,0.480466,0.320405,0.400528,2.049992,0.884419,1070976
1070976,1070976,0.015787,0.086075,0.529026,0.320871,0.431352,0.141083,0.269286,1.793481,0.817905,1070977
1070977,1070977,0.000701,0.072885,0.584835,0.184173,0.288086,0.108222,0.069024,1.307925,0.693350,1070978
1070978,1070978,0.015310,0.078009,0.504167,0.247759,0.396759,0.086625,0.244060,1.572688,0.739172,1070979
1070979,1070979,0.056606,0.137145,0.118517,0.152212,0.074449,0.180260,0.062722,0.781909,0.318116,1070980
1070980,1070980,0.000769,0.087914,0.468117,0.218804,0.330376,0.040638,0.174143,1.320759,0.644874,1070981
1070981,1070981,0.004676,0.086977,0.444405,0.268383,0.376082,0.139857,0.250648,1.571028,0.707767,1070982
1070982,1070982,0.027317,0.074017,0.525033,0.406478,0.479919,0.323510,0.361433,2.197707,0.955366,1070983
1070983,1070983,0.010384,0.097844,0.437054,0.370011,0.528246,0.344058,0.438663,2.226260,0.963043,1070984
1070984,1070984,0.022042,0.091085,0.430779,0.246740,0.401483,0.133696,0.281626,1.607452,0.716666,1070985
1070985,1070985,0.007539,0.094800,0.497074,0.252099,0.387742,0.067506,0.223319,1.530079,0.724191,1070986
1070986,1070986,0.012730,0.073812,0.541842,0.254317,0.407117,0.065618,0.234740,1.590176,0.767485,1070987
1070987,1070987,0.011248,0.073259,0.452401,0.186257,0.313931,0.028960,0.170993,1.237048,0.611131,1070988
1070988,1070988,0.033921,0.088491,0.520947,0.225615,0.403583,0.052007,0.239099,1.563665,0.744327,1070989
1070989,1070989,0.014933,0.092534,0.451401,0.219121,0.359946,0.057960,0.213777,1.409672,0.662709,1070990
1070990,1070990,0.007085,0.100524,0.402810,0.518651,0.684659,0.641868,0.664144,3.019741,1.327874,1070991
1070991,1070991,0.000488,0.098960,0.312818,0.622767,0.800749,0.908118,0.866127,3.610027,1.646676,1070992
1070992,1070992,0.002662,0.084835,0.512432,0.286140,0.408992,0.129412,0.257758,1.682232,0.775969,1070993
1070993,1070993,0.012627,0.065309,0.499523,0.129689,0.245279,0.115270,0.063882,1.131580,0.590167,1070994

In [22]:
newDF0=newDF.reset_index()
newDF0['index']=newDF0['index']+1

In [23]:
zscore = newDF0[['RECORD','Score1','Score2']]

In [24]:
zscore.sort_values('Score1')

          RECORD       Score1       Score2
185222    185223     0.159432     0.099564
200444    200445     0.166762     0.080115
184114    184115     0.166811     0.103342
184965    184966     0.174572     0.116966
878655    878656     0.176785     0.085718
181483    181484     0.179800     0.099529
181484    181485     0.179800     0.099529
163838    163839     0.181066     0.098636
163839    163840     0.181524     0.098724
484476    484477     0.181686     0.102841
154045    154046     0.181725     0.092316
1053229  1053230     0.182602     0.107654
249387    249388     0.185318     0.098944
225813    225814     0.188568     0.106619
185221    185222     0.189254     0.102503
228098    228099     0.189324     0.094704
151714    151715     0.189947     0.091844
1059397  1059398     0.190353     0.110362
998017    998018     0.192468     0.109339
332289    332290     0.193183     0.100826
957223    957224     0.196863     0.110607
226772    226773     0.196983     0.110435
243036    243037     0.197066     0.105021
904870    904871     0.197420     0.086451
999314    999315     0.198810     0.116008
917089    917090     0.199763     0.110231
1054198  1054199     0.201532     0.093045
170238    170239     0.201557     0.116000
1046472  1046473     0.202700     0.114747
156327    156328     0.203696     0.111608
...          ...          ...          ...
127152    127153   257.082016   149.530604
245572    245573   260.773291   123.080556
985596    985597   261.909952   115.723208
823223    823224   265.145040   126.443280
835932    835933   275.739569   140.710330
418          419   277.360461   137.431907
562741    562742   284.183970   151.446531
797935    797936   294.718260   137.475471
134442    134443   311.509484   139.152249
964933    964934   328.079703   153.619387
44247      44248   337.136290   187.362075
501142    501143   340.109428   163.651519
794104    794105   348.661035   162.491864
690832    690833   413.967379   202.431580
917941    917942   415.727941   186.220749
918203    918204   420.349280   174.447853
603584    603585   432.262585   189.757119
556608    556609   478.039767   232.943173
67128      67129   482.753268   225.517498
1067000  1067001   511.590139   234.894265
565397    565398   527.684682   219.219253
935157    935158   572.497926   256.849090
920627    920628   599.727105   283.407436
585119    585120   880.892554   405.602785
85885      85886  1001.493077   547.036855
585438    585439  1071.560298   518.660200
1067359  1067360  1335.959954   643.094180
585117    585118  1410.391617   649.069311
565391    565392  1874.226835   908.165895
632815    632816  1984.827452  1017.799493

[1070994 rows x 3 columns]

In [25]:
zscore[zscore['RECORD']==821853]

        RECORD      Score1     Score2
821852  821853  139.704215  98.665708

In [26]:
pd.DataFrame(zscore).to_csv('zscore.csv')